env:
  browser: true
  es2021: true
extends:
  - standard
parserOptions:
  ecmaVersion: 12
  sourceType: module
rules:
  comma-dangle: [error, only-multiline]
  new-cap: [error, { newIsCapExceptions: ["jBox"] }]

