/*
 * RTK - I'm doing it - that's that!
 * I accept it as the challenge it is.
 * I consider it to be a side-quest in my Japanese learning.
 *
 * Overcoming laziness as a learner.
 *
 * kanjivg and heisig-rtk-index
 *
 *
 */

import * as THREE from 'three'
import { GUI } from 'three/addons/libs/lil-gui.module.min.js'
import { MiniGameBase } from '../MiniGameBase'
import $ from 'jquery'

const sources = {
  gradedReaders: {
    first: {
      site: 'https://jgrpg-sakura.com/',
      info: 'needs registration and a test',
      me: `kumo no ito was a enlightening - I should go back and read it again
      Keita to neko ishi part one was also enlightening
      (enlightening as in the exciting light-bulb moment of things coming together)
      `
    }
  },
  JLPT_N5: {
    vocabulary: {
      list: 'https://nihongoichiban.com/2011/04/30/complete-list-of-vocabulary-for-the-jlpt-n5/',
      html: ''
    },
    videoList: {
      listName: 'Japanese Ammo with Misa JLPT N5 YouTube playlist (@JapaneseAmmowithMisa)',
      src: 'https://www.youtube.com/playlist?list=PLd5-Wp_4tLqaDGh1kvlS_N0X3O_bTaKar'
    },
    kanji: {
      rtkVsSchool: {
        situation: `

The RTK Kanji list is ordered to build up from a foundation but
that order is not frequency of usage or how important the Kanji is.

That may be a bit annoying.

RTK does not teach any Japanese readings - only conceptual meanings
and only associated with English words in order to create a mapping
of english word to Kanji _in that direction_!

The Kanji is taught in school to kids who quite naturally already
speak and understand the language, see those kanji symbols every day,
are free to ask anyone any questions about them, etc. etc.

There's a fixed order of learning. The learning is by repetition.


        `,
        items: {
          term: 'Kyōiku kanji',
          meaning: 'education kanji',
          wpPage: 'https://en.wikipedia.org/wiki/Ky%C5%8Diku_kanji',

        }

      }
    }
  }
}

class JapaneseStudy extends MiniGameBase {
  constructor (parent) {
    super(parent, 'Japanese Study')
    this.sources = sources
    parent.addEventListener('ready', (ev) => {
      this.onReady(ev)
      console.assert(this.gui instanceof GUI)
      console.assert(this.group instanceof THREE.Group)
      this.gui.add(this, 'runTest')
      this.gui.add(this, 'activate')
      this.gui.add(this, 'deactivate')
      this.gui.add(this, 'n5Kanji')
      // do more!
    })
  }

  //
  //
  async runTest () {
    console.warn('TODO runTest')
    const k = this.kanaGenerate()
    console.dir(k)
  }

  kanaGenerate () {
    const out = []
    const col = ' kstnhmyrw'.split('')
    const row = 'aiueo'.split('')
    for (let i = 0; i < col.length; i++) {
      for (let j = 0; j < row.length; j++) {
        out.push(`${col[i]}${row[j]}`)
      }
    }
    return out.map(x => x.trim())
  }

  n5Kanji () {
    const id = 'n5KanjiDiv'
    // toggle
    // if div exists
    const s = $(`#${id}`)
    if (s.length) {
      s.toggle()
      return
    }
    $(`<div id="${id}">Hello</div>`).appendTo('body')
  }

  getN5KanjiTab () {
    const tab = [
      ['Code', 'kanji', 'Onyomi', 'Kunyomi', 'Meaning'],
      ['5B89', '安', 'AN', 'yasu(i)', 'peace, cheap, safety'],
      ['4E00', '一', 'ICHI, ITSU', 'hito(tsu), hito-', 'one'],
      ['98F2', '飲', 'IN', 'no(mu)', 'to drink'],
      ['53F3', '右', 'U, YUU', 'migi', 'right'],
      ['96E8', '雨', 'U', 'ame', 'rain'],
      ['99C5', '駅', 'EKI', '–', 'station'],
      ['5186', '円', 'EN', 'maru(i)', 'circle, Yen, round'],
      ['706B', '火', 'KA', 'hi', 'fire'],
      ['82B1', '花', 'KA', 'hana', 'flower, blossom'],
      ['4E0B', '下', 'KA, GE', 'shimo, sa(geru), o(rosu), ku(daru)', 'below, down'],
      ['4F55', '何', 'KA', 'nani', 'what, how many, which'],
      ['4FLA', '会', 'KAI, E', 'a(u)', 'to meet, to come together, society'],
      ['5916', '外', 'GAI, GE', 'soto, hoka, hazu(reru), hazu(su)', 'outside, other, disconnect'],
      ['5B66', '学', 'GAKU', 'mana(bu)', 'school, science, learning'],
      ['9593', '間', 'KAN, KEN', 'aida', 'time, time span'],
      ['6C17', '気', 'KI, KE', '–', 'soul, spirit'],
      ['4E5D', '九', 'KYUU, KU', 'kokono(tsu), kokono-', 'nine'],
      ['4F11', '休', 'KYUU', 'yasu(mu)', 'to rest'],
      ['9B5A', '魚', 'GYO', 'sakana, uo', 'fish'],
      ['91D1', '金', 'KIN, KON', 'kane', 'gold, metal, money'],
      ['7A7A', '空', 'KUU', 'sora, a(keru), kara', 'sky, to become free, empty'],
      ['6708', '月', 'GETSU, GATSU', 'tsuki', 'month, moon'],
      ['898B', '見', 'KEN', 'mi(ru), mi(eru), mi(seru)', 'to see, to be visible, to show'],
      ['8A00', '言', 'GEN, GON', 'i(u)', 'word, to talk'],
      ['53E4', '古', 'KO', 'furu(i)', 'old, used'],
      ['4E94', '五', 'GO', 'itsu(tsu), itsu-', 'five'],
      ['5F8C', '後', 'GO, KOU', 'ato, oku(reru), nochi', 'after, later, back, to stay behind'],
      ['5348', '午', 'GO', '–', 'noon'],
      ['8A9E', '語', 'GO', 'kata(ru), kata(rau)', 'word, to talk'],
      ['6821', '校', 'KOU', '–', 'school'],
      ['53E3', '口', 'KOU, KU', 'kuchi', 'mouth'],
      ['884C', '行', 'KOU', 'i(ku), yu(ku), okona(u)', 'to walk. to go, to do, to carry out'],
      ['9AD8', '高', 'KOU', 'taka(i), taka(maru), taka(meru)', 'high, expensive, increase, quantity'],
      ['56FD', '国', 'KOKU', 'kuni', 'country'],
      ['4ECA', '今', 'KON, KIN', 'ima', 'now'],
      ['5DE6', '左', 'SA', 'hidari', 'left'],
      ['4E09', '三', 'SAN', 'mit(tsu), mi-', 'three'],
      ['5C71', '山', 'SAN', 'yama', 'mountain'],
      ['56DB', '四', 'SHI', 'yo(ttsu), yu(tsu), yo-, yon-', 'four'],
      ['5B50', '子', 'SHI, SU', 'ko', 'child'],
      ['8033', '耳', 'JI', 'mimi', 'ear'],
      ['6642', '時', 'JI', 'toki', 'time, hour'],
      ['4E03', '七', 'SHICHI', 'nana(tsu), nana-, nano-', 'seven'],
      ['8ECA', '車', 'SHA', 'kuruma', 'car, wheel'],
      ['793E', '社', 'SHA', 'yashiro', 'shinto shrine, society'],
      ['624B', '手', 'SHU', 'te', 'hand'],
      ['9031', '週', 'SHUU', '–', 'week'],
      ['5341', '十', 'JUU, JI', 'too, to-', 'ten, cross'],
      ['51FA', '出', 'SHUTSU', 'da(su), de(ru)', 'to leave, to get out. to take out'],
      ['66F8', '書', 'SHO', 'ka(ku)', 'to write'],
      ['5073', '女', 'JO, NYO', 'onna, me', 'woman, female'],
      ['5C0F', '小', 'SHOU', 'chii(sai), ko-, o-', 'small'],
      ['5C11', '少', 'SHOU', 'suko(shi), suku(nai)', 'a little'],
      ['4E0A', '上', 'SHOU, JOU', 'ue, kami, a(geru), a(garu)', 'above, upper'],
      ['98DF', '食', 'SHOKU', 'ta(beru), ku(ru), ku(rau)', 'to eat'],
      ['65B0', '新', 'SHIN', 'atara(shii), ara(ta), nii-', 'new'],
      ['4EBA', '人', 'JIN, NIN', 'hito', 'person'],
      ['6C34', '水', 'SUI', 'mizu', 'water'],
      ['751F', '生', 'SEI, SHOU', 'i(kiru), u(mu), ha(yasu), nama, ki', 'to live, to grow, to be born, raw'],
      ['897F', '西', 'SEI, SAI', 'nishi', 'west'],
      ['5DDD', '川', 'SEN', 'kawa', 'river'],
      ['5343', '千', 'SEN', 'chi', 'thousand'],
      ['5148', '先', 'SEN', 'saki', 'before, in future'],
      ['524D', '前', 'ZEN', 'mae', 'before'],
      ['8DB3', '足', 'SOKU', 'ashi, ta(riru), ta(su)', 'foot, to be sufficient, to add'],
      ['491A', '多', 'TA', 'oo(i)', 'many'],
      ['5927', '大', 'DAI, TAI', 'ou(kii), oo(i)', 'big, a lot'],
      ['7537', '男', 'DAN, NAN', 'otoko', 'man, male'],
      ['4E2D', '中', 'CHUU', 'naka', 'inner, center, between'],
      ['9577', '長', 'CHOU', 'naga(i)', 'long, leader'],
      ['5929', '天', 'TEN', 'ame, ama', 'sky'],
      ['5E97', '店', 'TEN', 'mise', 'shop'],
      ['96FB', '電', 'DEN', '–', 'electricity'],
      ['571F', '土', 'DO, TO', 'tsuchi', 'earth, ground'],
      ['6771', '東', 'TOU', 'higashi', 'east'],
      ['9053', '道', 'DOU', 'michi', 'street, path'],
      ['8AAD', '読', 'DOKU', 'yo(mu)', 'to read'],
      ['5357', '南', 'NAN', 'minami', 'south'],
      ['4E8C', 'ニ', 'NI', 'futa(tsu), futa-', 'two'],
      ['65E5', '日', 'NICHI, JITSU', 'hi, -ka', 'day, sun'],
      ['5165', '入', 'NYUU', 'hai(ru), i(ru), i(reru)', 'to enter, to insert'],
      ['5E74', '年', 'NEN', 'toshi', 'year'],
      ['8CB7', '買', 'BAI', 'ka(u)', 'to buy'],
      ['767D', '白', 'HAKU, BYAKU', 'shiro(i), shiro', 'white'],
      ['516B', '八', 'HACHI', 'yat(tsu), ya(tsu), ya-, you-', 'eight'],
      ['534A', '半', 'HAN', 'naka(ba)', 'half, middle, semi-'],
      ['767E', '百', 'HYAKU', '–', 'hundred'],
      ['7236', '父', 'FU', 'chichi', 'father'],
      ['5206', '分', 'BUN, BU, FUN', 'wa(keru), wa(kareru), wa(karu)', 'part, minute, to divide, to understand'],
      ['805E', '聞', 'BUN, MON', 'ki(ku), ki(koeru)', 'to hear, to listen, to ask'],
      ['6BCD', '母', 'BO', 'haha', 'mother'],
      ['5317', '北', 'HOKU', 'kita', 'north'],
      ['6728', '木', 'BOKU, MOKU', 'ki, ko', 'tree, wood'],
      ['672C', '本', 'HON', 'moto', 'book, source, main-'],
      ['6BCE', '毎', 'MAI', '–', 'each, every'],
      ['4E07', '万', 'MAN, BAN', '–', 'ten thousand, all, many'],
      ['540D', '名', 'MEI, MYOU', 'na', 'name, reputation'],
      ['76EE', '目', 'MOKU', 'me', 'eye'],
      ['53CB', '友', 'YUU', 'tomo', 'friend'],
      ['6765', '来', 'RAI', 'ku(ru), kita(ru), kita(su)', 'to come'],
      ['7ABC', '立', 'RITSU', 'ta(tsu), ta(teru)', 'to stand, to establish'],
      ['516D', '六', 'ROKU', 'mutt(su), mu(tsu), mu, mui', 'six'],
      ['8A71', '話', 'WA', 'hanashi, hana(su)', 'speech, to talk, story, conversation'],
    ]
    return tab
  }

  // using https://tableconvert.com/html-to-jsonlines to convert from a HTML table
  // the table ain't square - it is separated by single item rows indicating the start of a kana
  getN5Vocab () {
    const tab = [
      ['Kanji', 'Furigana', 'Romaji', 'Meaning'],

      ['a'],

      ['', '&nbsp;ああ', 'ah', '&nbsp;Ah!'],
      ['会う', 'あう', 'au', 'to meet'],
      ['青い\n                    ', '&nbsp;あおい', 'aoi', 'blue'],
      ['赤い\n                    ', 'あかい', 'akai', 'red'],
      ['&nbsp;明るい', 'あかるい', 'akarui', 'light, bright'],
      ['秋', 'あき', 'aki', 'autumn, fall'],
      ['開く', 'あく', 'aku', 'open'],
      ['開ける', 'あける', 'akeru', 'to open'],
      ['', 'あげる', 'ageru', 'to give'],
      ['朝', 'あさ', 'asa', 'morning'],
      ['朝ご飯', 'あさごはん', 'asagohan', 'breakfast'],
      ['あさって', 'あさって', 'asatte', 'the day after tomorrow'],
      ['&nbsp;足', 'あし', 'ashi', 'leg, foot'],
      ['明日\n                    ', 'あした', 'ashita', 'tomorrow'],
      ['あそこ', 'あそこ', 'asoko', 'over there'],
      ['遊ぶ', 'あそぶ', 'asobu', 'to play'],
      ['温かい', 'あたたかい', 'atatakai', 'warm'],
      ['頭', 'あたま', 'atama', 'head'],
      ['&nbsp;新しい', 'あたらしい', 'atarashii', 'new'],
      ['&nbsp;あちら', 'あちら', 'achira', 'over there (polite)'],
      ['暑い\n                    ', 'あつい', 'atsui', 'hot (air)'],
      ['厚い\n                    ', 'あつい', 'atsui', 'thick'],
      ['後', 'あと', 'ato', 'later, after'],
      ['&nbsp;貴方', 'あなた', 'anata', 'you'],
      ['兄', 'あに', 'ani', 'older brother'],
      ['姉', 'あね', 'ane', 'older sister'],
      ['あの', 'あの', 'ano', 'that (over there)'],
      ['あの', 'あの', 'ano', 'well, then'],
      ['アパート', 'アパート', 'apaato', 'apartment'],
      ['&nbsp;浴びる', 'あびる', 'abiru', 'to take a shower'],
      ['危ない', 'あぶない', 'abunai', 'dangerous'],
      ['甘い\n                    ', 'あまい', 'amai', 'sweet'],
      ['あまり', 'あまり', 'amari', 'not so'],
      ['&nbsp;雨', 'あめ', 'ame', 'rain'],
      ['&nbsp;洗う', 'あらう', 'arau', 'to wash'],
      ['&nbsp;有る', 'ある', 'aru', 'to be, to exist'],
      ['ある', 'ある', 'aru', 'to possess'],
      ['歩く', 'あるく', 'aruku', 'to walk'],
      ['あれ', 'あれ', 'are', 'that one'],

      ['i'],

      ['&nbsp;良い\n                    ', 'いい / よい', 'ii, yoi', 'good'],
      ['いいえ', 'いいえ', 'iie', 'no'],
      ['&nbsp;言う', 'いう', 'iu', 'to say, to tell'],
      ['家', 'いえ', 'ie', 'house, home'],
      ['行く', 'いく', 'iku', 'to go'],
      ['&nbsp;いくつ', 'いくつ', 'ikutsu', 'how many, how old'],
      ['いくら', 'いくら', 'ikura', 'how much'],
      ['池', 'いけ', 'ike', 'pond'],
      ['医者\n                    ', 'いしゃ', 'isha', 'doctor'],
      ['椅子', 'いす', 'isu', 'chair'],
      ['忙しい', 'いそがしい', 'isogashii', 'to be busy'],
      ['痛い\n                    ', 'いたい', 'itai', 'to be painful'],
      ['一', 'いち', 'ichi', 'one'],
      ['&nbsp;一日', 'いちにち', 'ichinichi', 'one day'],
      ['一番', 'いちばん', 'ichiban', 'No. 1, the best, the first'],
      ['いつ', 'いつ', 'itsu', 'when'],
      ['五日', 'いつか', 'itsuka', 'the 5th day of the month, 5 days'],
      ['&nbsp;一緒', 'いっしょ', 'issho', 'together'],
      ['五つ', 'いつつ', 'itsutsu', 'five'],
      ['いつも', 'いつも', 'itsumo', 'always'],
      ['今', 'いま', 'ima', 'now'],
      ['意味\n                    ', 'いみ', 'imi', 'meaning'],
      ['&nbsp;妹', 'いもうと', 'imouto', 'someone’s younger sister'],
      ['いや', 'いや', 'iya', 'not likable, unpleasant'],
      ['&nbsp;入口\n                    ', 'いりぐち', 'iriguchi', 'entrance'],
      ['', 'いる', 'iru', 'need, must have, be required'],
      ['', 'いる', 'iru', 'to exist'],
      ['入れる', 'いれる', 'ireru', 'to insert, to put in'],
      ['色', 'いろ', 'iro', 'color'],
      ['色々', 'いろいろ', 'iroiro', 'various'],

      ['u'],

      ['&nbsp;上', 'うえ', 'ue', 'top, on, above'],
      ['後ろ', 'うしろ', 'ushiro', 'back, rear, behind'],
      ['薄い', 'うすい', 'usui', 'thin'],
      ['歌', 'うた', 'uta', 'song'],
      ['歌う', 'うたう', 'utau', 'to sing'],
      ['内', 'うち', 'uchi', 'home'],
      ['&nbsp;生まれる', 'うまれる', 'umareru', 'to be born'],
      ['海', 'うみ', 'umi', 'sea'],
      ['売る', 'うる', 'uru', 'to sell'],
      ['上着\n                    ', 'うわぎ', 'uwagi', 'coat, jacket'],

      ['e'],

      ['絵', 'え', 'e', 'picture'],
      ['映画', 'えいが', 'eiga', 'movie'],
      ['映画館', 'えいがかん', 'eigakan', 'cinema'],
      ['英語', 'えいご', 'eigo', 'English language'],
      ['&nbsp;ええ', 'ええ', 'ee', 'Yes, I see'],
      ['駅', 'えき', 'eki', 'station'],
      ['エレベータ', 'エレベータ', 'erebeeta', 'elevator'],
      ['円', 'えん', 'en', 'Yen'],
      ['&nbsp;鉛筆', 'えんぴつ', 'enpitsu', 'pencil'],

      ['o'],

      ['&nbsp;御', 'お', 'o', 'honorific\n                            prefix'],
      ['美味しい', 'おいしい', 'oishii', 'tasty, delicious'],
      ['&nbsp;大きい', 'おおきい', 'ookii', 'big'],
      ['', 'おおぜい', '&nbsp;oozei', 'many people'],
      ['&nbsp;お母さん', 'おかあさん', 'okaasan', 'my own mother'],
      ['お菓子', 'おかし', 'okashi', 'confectionary, cake'],
      ['&nbsp;お金', 'おかね', 'okane', 'money'],
      ['起きる', 'おきる', 'okiru', 'to get up, to stand up'],
      ['&nbsp;置く', 'おく', 'oku', 'to put, to place'],
      ['奥さん', 'おくさん', 'okusan', 'someone’s wife'],
      ['送る', 'おくる', 'okuru', 'to send'],
      ['お酒', 'おさけ', 'osake', 'alcohol, sake'],
      ['お皿', 'おさら', 'osara', 'plate'],
      ['&nbsp;伯父さん', 'おじさん', 'ojisan', 'uncle'],
      ['おじいさん', '&nbsp;おじいさん', 'ojiisan', 'grand father'],
      ['押す', 'おす', 'osu', 'to push'],
      ['遅い', 'おそい', 'osoi', 'late, slow'],
      ['お茶', 'おちゃ', 'ocha', 'tea'],
      ['お手洗い', 'おてあらい', 'otearai', 'toilet, lavatory'],
      ['お父さん', 'おとうさん', 'otousan', 'father'],
      ['弟', 'おとうと', 'otouto', 'someone’s younger brother'],
      ['男', 'おとこ', 'otoko', 'man'],
      ['男の子', 'おとこのこ', 'otokonoko', 'boy'],
      ['一昨日', 'おととい', 'ototoi', 'the day before yesterday'],
      ['一昨年', 'おととし', 'ototoshi', 'the year before last'],
      ['大人', 'おとな', 'otona', 'adult'],
      ['&nbsp;お腹', 'おなか', 'onaka', 'stomach'],
      ['同じ', 'おなじ', 'onaji', 'same'],
      ['お兄さん', 'おにいさん', 'oniisan', 'someone’s elder brother'],
      ['お姉さん', 'おねえさん', 'oneesan', 'someone’s elder sister'],
      ['伯母さん', 'おばさん', 'obasan', 'aunt'],
      ['', 'おばあさん', 'obaasan', 'grandmother'],
      ['お弁当\n                    ', 'おべんとう', 'obentou', 'lunchbox'],
      ['覚える', 'おぼえる', 'oboeru', 'to memorize, to remember'],
      ['重い', 'おもい', 'omoi', 'heavy'],
      ['面白い', 'おもしろい', 'omoshiroi', 'interesting, funny'],
      ['泳ぐ', 'およぐ', 'oyogu', 'to swim'],
      ['降りる', 'おりる', 'oriru', 'to get off'],
      ['終わる', 'おわる', 'owaru', 'to end'],
      ['音楽', 'おんがく', 'ongaku', 'music'],
      ['女', 'おんな', 'onna', 'woman'],
      ['女の子', 'おんなのこ', 'onnanoko', 'girl'],

      ['ka'],

      ['〜回', '〜かい', '~kai', '~times'],
      ['〜階', '〜かい', '~kai', '~floor'],
      ['外国', 'がいこく', 'gaikoku', 'foreign country'],
      ['外国人', 'がいこくじん', 'gaikokujin', 'foreigner'],
      ['会社', 'かいしゃ', 'kaisha', 'company, enterprise'],
      ['階段', 'かいだん', 'kaidan', 'stairs'],
      ['&nbsp;買物', 'かいもの', 'kaimono', 'shopping'],
      ['買う', 'かう', 'kau', 'to buy'],
      ['返す', 'かえす', 'kaesu', 'to return an object'],
      ['帰る', 'かえる', 'kaeru', 'to return home'],
      ['顔', 'かお', 'kao', 'face'],
      ['', 'かかる', 'kakaru', 'to take time, money'],
      ['鍵', 'かぎ', 'kagi', 'key'],
      ['書く', 'かく', 'kaku', 'to write'],
      ['学生', 'がくせい', 'gakusei', 'student'],
      ['〜か月', '〜かげつ', '~kagetsu', '~ number of months'],
      ['', 'かける', 'kakeru', 'to wear'],
      ['', 'かける', 'kakeru', 'to make a phone call'],
      ['傘', 'かさ', 'kasa', 'umbrella'],
      ['貸す', 'かす', 'kasu', 'to lend'],
      ['風', 'かぜ', 'kaze', 'wind'],
      ['風邪', 'かぜ', 'kaze', 'a cold'],
      ['家族', 'かぞく', 'kazoku', 'family'],
      ['方', 'かた', 'kata', 'person (polite)'],
      ['片仮名', 'かたかな', 'katakana', 'Katakana'],
      ['一月', 'いちがつ', 'ichigatsu', 'January'],
      ['二月', 'にがつ', 'nigatsu', 'February'],
      ['三月', 'さんがつ', 'sangatsu', 'March'],
      ['四月', 'しがつ', 'shigatsu', 'April'],
      ['五月', 'ごがつ', 'gogatsu', 'May'],
      ['六月', 'ろくがつ', 'rokugatsu', 'June'],
      ['七月', 'しちがつ', 'shichigatsu', 'July'],
      ['八月', 'はちがつ', 'hachigatsu', 'August'],
      ['九月', 'くがつ', 'kugatsu', 'September'],
      ['十月', 'じゅうがつ', 'juugatsu', 'October'],
      ['十一月', 'じゅういちがつ', 'juuichigatsu', 'November'],
      ['十二月', 'じゅうにがつ', 'juunigatsu', 'December'],
      ['学校', 'がっこう', 'gakkou', 'school'],
      ['角', 'かど', 'kado', 'corner'],
      ['家内', 'かない', 'kanai', 'my wife'],
      ['鞄', 'かばん', 'kaban', 'bag'],
      ['花瓶', 'かびん', 'kabin', 'vase'],
      ['冠る', 'かぶる', 'kaburu', 'to put on a hat'],
      ['紙', 'かみ', 'kami', 'paper'],
      ['カメラ', 'かめら', 'kamera', 'camera'],
      ['火曜日', 'かようび', 'kayoubi', 'Tuesday'],
      ['辛い', 'からい', 'karai', 'hot, spicy'],
      ['体', 'からだ', 'karada', 'body'],
      ['借りる', 'かりる', 'kariru', 'to borrow'],
      ['', '〜がります', '~garimasu', '3rd person wants to'],
      ['軽い', 'かるい', 'karui', 'light (not heavy)'],
      ['カレンダー', 'カレンダー', 'karendaa', '&nbsp;calendar'],
      ['川', 'かわ', 'kawa', 'river'],
      ['&nbsp;〜側', '&nbsp;~がわ', '~gawa', '~side'],
      ['可愛い', 'かわいい', 'kawaii', 'cute, pretty'],
      ['漢字', 'かんじ', 'kanji', 'Kanji character'],

      ['ki'],

      ['木', 'き', 'ki', 'tree'],
      ['黄色い', 'きいろい', 'kiiroi', 'yellow'],
      ['消える', 'きえる', 'kieru', 'to go out, to vanish'],
      ['聞く', 'きく', 'kiku', 'to hear, to listen, to ask'],
      ['北', 'きた', 'kita', 'north'],
      ['ギター', 'ギター', 'gitaa', 'guitar'],
      ['汚い', 'きたない', 'kitanai', 'dirty'],
      ['喫茶店', 'きっさてん', 'kissaten', 'coffee shop'],
      ['切手', 'きって', 'kitte', 'stamp'],
      ['切符', 'きっぷ', 'kippu', 'ticket'],
      ['昨日', 'きのう', 'kinou', 'yesterday'],
      ['九', 'きゅう', 'kyuu', 'nine'],
      ['牛肉', 'ぎゅうにく', 'gyuuniku', 'beef'],
      ['牛乳', 'ぎゅうにゅう', 'gyuunyuu', 'milk'],
      ['今日', 'きょう', 'kyou', 'today'],
      ['教室', 'きょうしつ', 'kyoushitsu', 'class room'],
      ['兄弟', 'きょうだい', 'kyoudai', 'siblings'],
      ['去年', 'きょねん', 'kyonen', 'last year'],
      ['嫌い', 'きらい', 'kirai', 'unpleasant, not likable'],
      ['切る', 'きる', 'kiru', 'to cut'],
      ['着る', 'きる', 'kiru', 'to wear, to put on'],
      ['来る', 'くる', 'kuru', 'to come'],
      ['', 'きれい', 'kirei', 'beautiful, clean'],
      ['キロ', 'キロ', 'kiro', 'kg'],
      ['キロ', 'キロ', 'kiro', 'km'],
      ['銀行', 'ぎんこう', 'ginkou', 'bank'],
      ['金曜日', 'きんようび', 'kinyoubi', 'Friday'],

      ['ku'],

      ['九', 'く', 'ku', 'nine'],
      ['薬', 'くすり', 'kusuri', 'medicine'],
      ['下さい', 'ください', 'kudasai', 'give me…'],
      ['果物', 'くだもの', 'kudamono', 'fruit'],
      ['口', 'くち', 'kuchi', 'mouth'],
      ['靴', 'くつ', 'kutsu', 'shoe'],
      ['靴下', 'くつした', 'kutsushita', 'socks'],
      ['国', 'くに', 'kuni', 'country'],
      ['曇り', 'くもり', 'kumori', 'cloudy weather'],
      ['暗い', 'くらい', 'kurai', 'dark'],
      ['ぐらい', 'ぐらい', 'gurai', 'about'],
      ['クラス', 'クラス', 'kurasu', 'class'],
      ['グラム', 'グラム', 'guramu', 'gram'],
      ['車', 'くるま', 'kuruma', 'car'],
      ['黒い', 'くろい', 'kuroi', 'black'],

      ['ke'],

      ['今朝', 'けさ', 'kesa', 'this morning'],
      ['消す', 'けす', 'kesu', 'to turn off, switch off'],
      ['', 'けっこう', 'kekkou', 'fine, all right'],
      ['結婚', 'けっこん', 'kekkon', 'marriage'],
      ['月曜日', 'げつようび', 'getsuyoubi', 'Monday'],
      ['玄関', 'げんかん', 'genkan', 'entrance of a house'],
      ['元気', 'げんき', 'genki', 'vigor, health, vitality'],

      ['ko'],

      ['〜個', '〜こ', '~ko', 'counter for small objects'],
      ['五', 'ご', 'go', 'five'],
      ['〜語', '〜ご', '~go', '~ language'],
      ['公園', 'こうえん', 'kouen', 'park, large garden'],
      ['交番', 'こうばん', 'kouban', 'police box'],
      ['声', 'こえ', 'koe', 'voice'],
      ['コート', 'コート', 'kooto', 'coat'],
      ['ここ', 'ここ', 'koko', 'here'],
      ['午後', 'ごご', 'gogo', 'afternoon'],
      ['九日', 'ここのか', 'kokonoka', '9th day of a month, 9 days'],
      ['九つ', 'ここのつ', 'kokonotsu', 'nine'],
      ['ご主人', 'ごしゅじん', 'goshujin', 'someone else’s husband'],
      ['午前', 'ごぜん', 'gozen', 'morning, a.m.'],
      ['答える', 'こたえる', 'kotaeru', 'to answer'],
      ['こちら', 'こちら', 'kochira', 'this side, this place'],
      ['コップ', 'コップ', 'koppu', 'cup, glass'],
      ['今年', 'ことし', 'kotoshi', 'this year'],
      ['言葉', 'ことば', 'kotoba', 'phrase, language'],
      ['子供', 'こども', 'kodomo', 'child'],
      ['この', 'この', 'kono', 'this…'],
      ['御飯', 'ごはん', 'gohan', 'meal, cooked rice'],
      ['困る', 'こまる', 'komaru', 'to be in trouble'],
      ['これ', 'これ', 'kore', 'this'],
      ['ごろ', 'ごろ', 'goro', 'around…'],
      ['今月', 'こんげつ', 'kongetsu', 'this month'],
      ['今週', 'こんしゅう', 'konshuu', 'this week'],
      ['こんな', 'こんな', 'konna', 'this sort of, this kind of'],
      ['今晩', 'こんばん', 'konban', 'this evening'],

      ['sa'],

      ['さあ', 'さあ', 'saa', 'well…'],
      ['〜歳', '〜さい', '~sai', 'years old'],
      ['魚', 'さかな', 'sakana', 'fish'],
      ['先', 'さき', 'saki', 'earlier, former'],
      ['咲く', 'さく', 'saku', 'to blossom'],
      ['作文', 'さくぶん', 'sakubun', 'composition'],
      ['', 'さす', 'sasu', 'to open an umbrella'],
      ['冊', '〜さつ', '~satsu', 'counter for books'],
      ['雑誌', 'ざっし', 'zasshi', 'magazine'],
      ['砂糖', 'さとう', 'satou', 'sugar'],
      ['寒い', 'さむい', 'samui', 'cold'],
      ['再来年', 'さらいねん', 'sarainen', 'the year after next year'],
      ['三', 'さん', 'san', 'three'],
      ['〜さん', '〜さん', '~san', 'Mr., Mrs.'],
      ['散歩', 'さんぽ', 'sanpo', 'to take a walk'],

      ['shi'],

      ['四', 'し', 'shi', 'four'],
      ['〜時', '〜じ', '~ji', 'o’clock'],
      ['塩', 'しお', 'shio', 'salt'],
      ['しかし', 'しかし', 'shikashi', 'however, but'],
      ['時間', 'じかん', 'jikan', 'time'],
      ['〜時間', '〜じかん', '~jikan', '~hours (classificator)'],
      ['仕事', 'しごと', 'shigoto', 'work'],
      ['辞書', 'じしょ', 'jisho', 'dictionary'],
      ['静か', 'しずか', 'shizuka', 'quiet'],
      ['下', 'した', 'shita', 'under, below'],
      ['質問', 'しつもん', 'shitsumon', 'question'],
      ['自転車', 'じてんしゃ', 'jitensha', 'bicycle'],
      ['自動車', 'じどうしゃ', 'jidousha', 'car, vehicle'],
      ['死ぬ', 'しぬ', 'shinu', 'to die, to pas away'],
      ['字引', 'じびき', 'jibiki', 'dictionary'],
      ['自分', 'じぶん', 'jibun', 'oneself'],
      ['閉まる', 'しまる', 'shimaru', 'to close'],
      ['閉める', 'しめる', 'shimeru', 'to close'],
      ['締める', 'しめる', 'shimeru', 'to fasten a seatbelt'],
      ['じゃ', 'じゃ', 'ja', 'well, then'],
      ['写真', 'しゃしん', 'shashin', 'photo'],
      ['シャツ', 'シャツ', 'shatsu', 'shirt'],
      ['十', 'じゅう', 'juu', 'ten'],
      ['~週間', '〜しゅうかん', '~shuukan', '… weeks'],
      ['授業', 'じゅぎょう', 'jugyou', 'lesson, class'],
      ['宿題', 'しゅくだい', 'shukudai', 'homework'],
      ['上手', 'じょうず', 'jouzu', 'to be good at something'],
      ['丈夫', 'じょうぶ', 'joubu', 'to be strong, durable'],
      ['醤油', 'しょうゆ', 'shouyu', 'soy sauce'],
      ['食堂', 'しょくどう', 'shokudou', 'dining room, canteen'],
      ['知る', 'しる', 'shiru', 'to know'],
      ['白い', 'しろい', 'shiroi', 'white'],
      ['〜人', '〜じん', '~jin', '~an, ~ese (nationality)'],
      ['新聞', 'しんぶん', 'shinbun', 'newspaper'],

      ['su'],

      ['水曜日', 'すいようび', 'suiyoubi', 'Wednesday'],
      ['吸う', 'すう', 'suu', 'to breathe, to smoke'],
      ['スカート', 'スカート', 'sukaato', 'skirt'],
      ['好き', 'すき', 'suki', 'to like'],
      ['〜過ぎ', '〜すぎ', '~sugi', 'past, over'],
      ['すぐに', 'すぐに', 'sugu ni', 'at once'],
      ['少し', 'すこし', 'sukoshi', 'a little'],
      ['涼しい', 'すずしい', 'suzushii', 'cool'],
      ['〜ずつ', '〜ずつ', '~zutsu', 'each'],
      ['ストーブ', 'ストーブ', 'sutoobu', 'stove, heater'],
      ['スプーン', 'スプーン', 'supuun', 'spoon'],
      ['スポーツ', 'スポーツ', 'supootsu', 'sports'],
      ['ズボン', 'ズボン', 'zubon', 'trousers'],
      ['住む', 'すむ', 'sumu', 'to live, to reside somewhere'],
      ['スリッパ', 'スリッパ', 'surippa', 'slipper'],
      ['する', 'する', 'suru', 'to do'],
      ['座る', 'すわる', 'suwaru', 'to sit'],

      ['se'],

      ['背', 'せい', 'sei', 'height'],
      ['生徒', 'せいと', 'seito', 'student'],
      ['セーター', 'セーター', 'seetaa', 'sweater'],
      ['石鹸', 'せっけん', 'sekken', 'soap'],
      ['背広', 'せびろ', 'sebiro', 'jacket, suit'],
      ['狭い', 'せまい', 'semai', 'narrow'],
      ['ゼロ', 'ゼロ', 'zero', 'zero'],
      ['千', 'せん', 'sen', '1,000, thousand'],
      ['先月', 'せんげつ', 'sengetsu', 'last month'],
      ['先週', 'せんしゅう', 'senshuu', 'last week'],
      ['先生', 'せんせい', 'sensei', 'teacher'],
      ['洗濯', 'せんたく', 'sentaku', 'washing, to wash'],
      ['全部', 'ぜんぶ', 'zenbu', 'all'],

      ['so'],

      ['そう', 'そう', 'sou', 'so'],
      ['掃除', 'そうじ', 'souji', 'to clean'],
      ['そうして', 'そうして', 'soushite', 'and then'],
      ['そこ', 'そこ', 'soko', 'there'],
      ['そちら', 'そちら', 'sochira', 'there (polite)'],
      ['外', 'そと', 'soto', 'outside'],
      ['その', 'その', 'sono', 'that…'],
      ['そば', 'そば', 'soba', 'next to'],
      ['空', 'そら', 'sora', 'sky'],
      ['それ', 'それ', 'sore', 'that'],
      ['それから', 'それから', 'sorekara', 'after that'],
      ['それでは', 'それでは', 'soredewa', 'then, well'],

      ['ta'],

      ['〜台', '〜だい', '~dai', 'counter for machines'],
      ['大学', 'だいがく', 'daigaku', 'university'],
      ['大使館', 'たいしかん', 'taishikan', 'embassy'],
      ['大丈夫', 'だいじょうぶ', 'daijoubu', 'OK'],
      ['大好き', 'だいすき', 'daisuki', 'to be very fond of'],
      ['大切', 'たいせつ', 'taisetsu', 'very important'],
      ['', 'たいてい', 'taitei', 'mostly, usually'],
      ['台所', 'だいどころ', 'daidokoro', 'kitchen'],
      ['大変', 'たいへん', 'taihen', 'very, serious'],
      ['高い', 'たかい', 'takai', 'high, expensive'],
      ['沢山', 'たくさん', 'takusan', 'many, much'],
      ['タクシー', 'タクシー', 'takushii', 'taxi'],
      ['出す', 'だす', 'dasu', 'to take out, hand in'],
      ['~達', '〜たち', '~tachi', 'more than one, and others'],
      ['立つ', 'たつ', 'tatsu', 'to stand'],
      ['建物', 'たてもの', 'tatemono', 'building'],
      ['楽しい', 'たのしい', 'tanoshii', 'pleasant, enjoyable'],
      ['頼む', 'たのむ', 'tanomu', 'to ask, to request'],
      ['たばこ', 'たばこ', 'tabako', 'cigarette'],
      ['多分', 'たぶん', 'tabun', 'perhaps, probably'],
      ['食べ物', 'たべもの', 'tabemono', 'food'],
      ['食べる', 'たべる', 'taberu', 'to eat'],
      ['卵', 'たまご', 'tamago', 'egg'],
      ['誰', 'だれ', 'dare', 'who?'],
      ['誕生日', 'たんじょうび', 'tanjoubi', 'birthday'],
      ['だんだん', 'だんだん', 'dandan', 'gradually'],

      ['chi'],

      ['小さい', 'ちいさい', 'chiisai', 'small'],
      ['近い', 'ちかい', 'chikai', 'near, close'],
      ['違う', 'ちがう', 'chigau', 'different'],
      ['地下鉄', 'ちかてつ', 'chikatetsu', 'subway'],
      ['地図', 'ちず', 'chizu', 'map'],
      ['父', 'ちち', 'chichi', 'my father'],
      ['茶色', 'ちゃいろ', 'chairo', 'brown'],
      ['茶碗', 'ちゃわん', 'chawan', 'rice bowl'],
      ['〜中', '〜ちゅう', '~chuu', 'in the middle of'],
      ['ちょうど', 'ちょうど', 'choudo', 'just'],
      ['ちょっと', 'ちょっと', 'chotto', 'a little'],

      ['tsu'],

      ['一日', 'ついたち', 'tsuitachi', 'the 1st day of a month'],
      ['使う', 'つかう', 'tsukau', 'to use'],
      ['疲れる', 'つかれる', 'tsukareru', 'to get tired'],
      ['次', 'つぎ', 'tsugi', 'next'],
      ['着く', 'つく', 'tsuku', 'to arrive'],
      ['机', 'つくえ', 'tsukue', 'table'],
      ['作る', 'つくる', 'tsukuru', 'to make, to produce'],
      ['点ける', 'つける', 'tsukeru', 'to turn on'],
      ['勤める', 'つとめる', 'tsutomeru', 'to work for someone'],
      ['詰らない', 'つまらない', 'tsumaranai', 'uninteresting'],
      ['冷たい', 'つめたい', 'tsumetai', 'cold'],
      ['強い', 'つよい', 'tsuyoi', 'strong'],

      ['te'],

      ['手', 'て', 'te', 'hand'],
      ['テープ', 'テープ', 'teepu', 'tape'],
      ['テープレコーダー', 'テープレコーダー', '&nbsp;teepu rekoodaa', 'tape recorder'],
      ['テーブル', 'テーブル', 'teeburu', 'table'],
      ['出かける', 'でかける', 'dekakeru', 'to go out'],
      ['手紙', 'てがみ', 'tegami', 'letter'],
      ['出来る', 'できる', 'dekiru', 'can'],
      ['出口', 'でぐち', 'deguchi', 'exit'],
      ['テスト', 'テスト', 'tesuto', 'test'],
      ['では', 'では', 'dewa', 'then, well'],
      ['デパート', 'デパート', 'depaato', 'department store'],
      ['でも', 'でも', 'demo', 'but'],
      ['出ます', 'でます', 'demasu', 'to leave'],
      ['テレビ', 'テレビ', 'terebi', 'TV'],
      ['天気', 'てんき', 'tenki', 'weather'],
      ['電気', 'でんき', 'denki', 'electricity'],
      ['電車', 'でんしゃ', 'densha', 'train'],
      ['電話', 'でんわ', 'denwa', 'phone'],

      ['to'],

      ['戸', 'と', 'to', 'door'],
      ['〜度', '〜ど', '~do', '~times, ~degree'],
      ['ドア', 'ドア', 'doa', 'door'],
      ['トイレ', 'トイレ', 'toire', 'toilet, lavatory'],
      ['どう', 'どう', 'dou', 'how?'],
      ['どうして', 'どうして', 'doushite', 'why?'],
      ['どうぞ', 'どうぞ', 'douzo', 'please, here you are'],
      ['動物', 'どうぶつ', 'doubutsu', 'animal'],
      ['どうも', 'どうも', 'doumo', 'thanks'],
      ['十', 'とお', 'too', 'ten'],
      ['遠い', 'とおい', 'tooi', 'far'],
      ['十日', 'とおか', 'tooka', 'the 10th day of a month, 10 days'],
      ['時々', 'ときどき', 'tokidoki', 'sometimes'],
      ['時計', 'とけい', 'tokei', 'watch, clock'],
      ['どこ', 'どこ', 'doko', 'where?'],
      ['所', 'ところ', 'tokoro', 'place'],
      ['図書館', 'としょかん', 'toshokan', 'library'],
      ['どちら', 'どちら', 'dochira', 'which, where (polite)'],
      ['とても', 'とても', 'totemo', 'very much, quiet'],
      ['どなた', 'どなた', 'donata', 'who (polite)'],
      ['隣り', 'となり', 'tonari', 'next to'],
      ['どの', 'どの', 'dono', 'which?'],
      ['飛ぶ', 'とぶ', 'tobu', 'to fly'],
      ['止まる', 'とまる', 'tomaru', 'to stop'],
      ['友達', 'ともだち', 'tomodachi', 'friend'],
      ['土曜日', 'どようび', 'doyoubi', 'Saturday'],
      ['鳥', 'とり', 'tori', 'bird'],
      ['鶏肉', 'とりにく', 'toriniku', 'chicken meat'],
      ['取る', 'とる', 'toru', 'to take'],
      ['撮る', 'とる', 'toru', 'to take a photo'],
      ['どれ', 'どれ', 'dore', 'which?'],
      ['どんな', 'どんな', 'donna', 'what kind of?'],

      ['na'],

      ['ナイフ', 'ナイフ', 'naifu', 'knife'],
      ['中', 'なか', 'naka', 'inside'],
      ['長い', 'ながい', 'nagai', 'long'],
      ['鳴く', 'なく', 'naku', 'to sing, mew, moo'],
      ['夏', 'なつ', 'natsu', 'summer'],
      ['夏休み', 'なつやすみ', 'natsuyasumi', 'summer vacation'],
      ['〜など', '〜など', '~nado', 'and so on'],
      ['七つ', 'ななつ', 'nanatsu', 'seven'],
      ['何', 'なに', 'nani', 'what?'],
      ['七日', 'なのか', 'nanoka', 'the 7th of a month, 7 days'],
      ['名前', 'なまえ', 'namae', 'name'],
      ['習う', 'ならう', 'narau', 'to learn'],
      ['並ぶ', 'ならぶ', 'narabu', 'to form a line'],
      ['並べる', 'ならべる', 'naraberu', 'to line up'],
      ['', 'なる', 'naru', 'to become'],

      ['ni'],

      ['二', 'に', 'ni', 'two'],
      ['賑やか', 'にぎやか', 'nigiyaka', 'lively'],
      ['お肉', 'おにく', 'oniku', 'meat'],
      ['西', 'にし', 'nishi', 'west'],
      ['〜日', '〜にち', '~nichi', '…st, ..nd, ..th'],
      ['日曜日', 'にちようび', 'nichiyoubi', 'Sunday'],
      ['荷物', 'にもつ', 'nimotsu', 'luggage'],
      ['ニュース', 'ニュース', 'nyuusu', 'news'],
      ['庭', 'にわ', 'niwa', 'garden'],
      ['〜人', '~にん', '~nin', '… people'],

      ['nu'],

      ['脱ぐ', 'ぬぐ', 'nugu', 'to take off clothes'],

      ['ne'],

      ['ネクタイ', 'ネクタイ', 'nekutai', 'necktie'],
      ['寝る', 'ねる', 'neru', 'to go to bed'],
      ['〜年', '〜ねん', '~nen', '~years'],

      ['no'],

      ['ノート', 'ノート', 'nooto', 'notebook'],
      ['登る', 'のぼる', 'noboru', 'to climb up'],
      ['飲物', 'のみもの', 'nomimono', 'drinks'],
      ['飲む', 'のむ', 'nomu', 'to drink'],
      ['乗る', 'のる', 'noru', 'to take, to ride'],

      ['ha'],

      ['歯', 'は', 'ha', 'teeth'],
      ['パーテイー', 'パーテイー', 'paateii', 'party'],
      ['はい', 'はい', 'hai', 'yes'],
      ['〜はい', '〜はい', '~hai', 'cups of ~'],
      ['灰皿', 'はいざら', 'haizara', 'ashtray'],
      ['入る', 'はいる', 'hairu', 'to enter'],
      ['葉書', 'はがき', 'hagaki', 'postcard'],
      ['履く', 'はく', 'haku', 'to put on shoes'],
      ['箱', 'はこ', 'hako', 'box'],
      ['橋', 'はし', 'hashi', 'bridge'],
      ['箸', 'はし', 'hashi', 'chopsticks'],
      ['始まる', 'はじまる', 'hajimaru', 'to begin, to start'],
      ['始め', 'はじめ', 'hajime', 'start, the beginning'],
      ['初めて', 'はじめて', 'hajimete', 'for the first time'],
      ['走る', 'はしる', 'hashiru', 'to run'],
      ['バス', 'バス', 'basu', 'bus'],
      ['バター', 'バター', 'bataa', 'butter'],
      ['二十歳', 'はたち', 'hatachi', '20 years old'],
      ['働く', 'はたらく', 'hataraku', 'to work'],
      ['八', 'はち', 'hachi', 'eight'],
      ['二十日', 'はつか', 'hatsuka', 'the 20th of the month, 20 days'],
      ['花', 'はな', 'hana', 'flower'],
      ['鼻', 'はな', 'hana', 'nose'],
      ['話', 'はなし', 'hanashi', 'conversation, tale'],
      ['話す', 'はなす', 'hanasu', 'to talk, to speak, to tell'],
      ['母', 'はは', 'haha', 'my mother'],
      ['早い', 'はやい', 'hayai', 'early'],
      ['速い', 'はやい', 'hayai', 'fast, quick'],
      ['&nbsp;春', 'はる', 'haru', 'spring'],
      ['張る', 'はる', 'haru', 'to put something on, to stick'],
      ['晴れる', 'はれる', 'hareru', 'to clear up'],
      ['〜半', '〜はん', '~han', 'Half~'],
      ['晩', 'ばん', 'ban', 'evening'],
      ['~番', '〜ばん', '~ban', 'No.~, ranking'],
      ['パン', 'パン', 'pan', 'bread'],
      ['ハンカチ', 'ハンカチ', 'hankachi', 'handkerchief'],
      ['番号', 'ばんごう', 'bangou', 'number'],
      ['晩ご飯', 'ばんごはん', 'bangohan', 'dinner'],
      ['半分', 'はんぶん', 'hanbun', 'half'],

      ['hi'],

      ['Kanji', 'Furigana', 'Romaji', 'Meaning'],
      ['東', 'ひがし', 'higashi', 'east'],
      ['〜匹', '〜ひき', '~hiki', 'counter for animals'],
      ['引く', 'ひく', 'hiku', 'to pull'],
      ['弾く', 'ひく', 'hiku', 'to play (an instrument)'],
      ['低い', 'ひくい', 'hikui', '&nbsp;low'],
      ['飛行機', 'ひこうき', 'hikouki', 'plane'],
      ['左', 'ひだり', 'hidari', 'left'],
      ['人', 'ひと', 'hito', 'person'],
      ['一つ', 'ひとつ', 'hitotsu', 'one'],
      ['一月', 'ひとつき', 'hitotsuki', 'one month'],
      ['一人', 'ひとり', 'hitori', 'one person'],
      ['暇', '&nbsp;ひま', 'hima', 'free time, leisure'],
      ['百', 'ひゃく', 'hyaku', 'hundred'],
      ['病院', 'びょういん', 'byouin', 'hospital'],
      ['病気', 'びょうき', 'byouki', 'ill, sick'],
      ['&nbsp;平仮名', 'ひらがな', 'hiragana', 'hiragana characters'],
      ['昼', 'ひる', 'hiru', 'noon'],
      ['昼ご飯', 'ひるごはん', 'hirugohan', 'lunch'],
      ['広い', 'ひろい', 'hiroi', 'wide, spacious'],

      ['fu'],

      ['フィルム', 'フィルム', 'firumu', 'film'],
      ['封筒', 'ふうとう', 'fuutou', 'envelope'],
      ['プール', 'プール', 'puuru', 'pool'],
      ['フォーク', 'フォーク', 'fooku', 'fork'],
      ['吹く', 'ふく', 'fuku', 'to blow (wind)'],
      ['服', 'ふく', 'fuku', 'clothes'],
      ['二つ', 'ふたつ', 'futatsu', 'two'],
      ['豚肉', 'ぶたにく', 'butaniku', 'pork'],
      ['二人', 'ふたり', 'futari', 'two people'],
      ['二日', 'ふつか', 'futsuka', '2nd day of the month, 2 days'],
      ['太い', 'ふとい', 'futoi', 'thick, fat'],
      ['降る', 'ふる', 'furu', 'to fall (rain, snow)'],
      ['古い', 'ふるい', 'furui', 'old'],
      ['お風呂', 'おふろ', 'ofuro', 'bath'],
      ['〜分', '〜ふん', '~fun', '~minutes'],

      ['he'],

      ['ページ', 'ページ', 'peeji', 'page'],
      ['下手', 'へた', 'heta', 'not good at something'],
      ['ベッド', 'ベッド', 'beddo', 'bed'],
      ['部屋', 'へや', 'heya', 'room'],
      ['辺', 'へん', 'hen', 'side, part, area'],
      ['ペン', 'ぺん', 'pen', 'pen'],
      ['勉強', 'べんきょう', 'benkyou', 'to study'],
      ['便利', 'べんり', 'benri', 'convenient'],

      ['ho'],

      ['方', 'ほう', 'hou', '~より〜のほうが〜'],
      ['帽子', 'ぼうし', 'boushi', 'hat'],
      ['ボールペン', 'ボールペン', 'boorupen', 'ballpen'],
      ['他', 'ほか', 'hoka', 'another, other'],
      ['ポケット', 'ポケット', 'poketto', 'pocket'],
      ['欲しい', 'ほしい', 'hoshii', 'to want something'],
      ['細い', 'ほそい', 'hosoi', 'thin, fine'],
      ['ボタン', 'ボタン', 'botan', 'button'],
      ['ホテル', 'ホテル', 'hoteru', 'hotel'],
      ['本', 'ほん', 'hon', 'book'],
      ['〜本', '~ほん', '~hon', 'counter for long objects'],
      ['本棚', 'ほんだな', 'hondana', 'bookshelf'],
      ['本当に', 'ほんとうに', 'hontouni', 'really'],

      ['ma'],

      ['〜枚', '〜まい', '~mai', 'counter for thin objects'],
      ['毎朝', 'まいあさ', 'maiasa', 'every morning'],
      ['毎月', 'まいつき/まいげつ', 'maitsuki/maigetsu', 'every month'],
      ['毎週', 'まいしゅう', 'maishuu', 'every week'],
      ['毎日', 'まいにち', 'mainichi', 'every day'],
      ['毎年', 'まいとし/まいねん', 'maitoshi/mainen', 'every year'],
      ['毎晩', 'まいばん', 'maiban', 'every evening'],
      ['前', 'まえ', 'mae', 'front'],
      ['〜前', '〜まえ', '~mae', 'before, in front of'],
      ['曲がる', 'まがる', 'magaru', 'to turn'],
      ['不味い', 'まずい', 'mazui', 'bad tasting'],
      ['また', 'また', 'mata', 'also, again'],
      ['まだ', 'まだ', 'mada', 'not yet'],
      ['町', 'まち', 'machi', 'city, town'],
      ['待つ', 'まつ', 'matsu', 'to wait'],
      ['真直ぐに', 'まっすぐに', 'massugu ni', 'straight ahead'],
      ['マッチ', 'マッチ', 'machi', 'matches'],
      ['窓', 'まど', 'mado', 'window'],
      ['丸い', 'まるい', 'marui', 'round'],
      ['万', 'まん', 'man', 'ten thousand'],
      ['万年筆', 'まんねんひつ', 'mannenhitsu', 'fountain pen'],

      ['mi'],

      ['磨く', 'みがく', 'migaku', 'to polish, to brush'],
      ['右', 'みぎ', 'migi', 'right'],
      ['短い', 'みじかい', 'mijikai', 'short'],
      ['お水', 'おみず', 'omizu', 'water'],
      ['店', 'みせ', 'mise', 'shop'],
      ['見せる', 'みせる', 'miseru', 'to look, to watch'],
      ['道', 'みち', 'michi', 'road'],
      ['三日', 'みっか', 'mikka', '3rd day of a month, 3 days'],
      ['三つ', 'みっつ', 'mittsu', 'three'],
      ['皆さん', 'みなさん', 'minsan', 'everyone'],
      ['南', 'みなみ', 'minami', 'south'],
      ['耳', 'みみ', 'mimi', 'ear'],
      ['見る', 'みる', 'miru', 'to see, to watch'],
      ['皆', 'みんな', 'minna', 'all, everyone'],

      ['mu'],

      ['六日', 'むいか', 'muika', 'the 6th day of a month, 6 days'],
      ['向こう', 'むこう', 'mukou', 'over there'],
      ['難しい', 'むずかしい', 'muzukashii', 'difficult'],
      ['六つ', 'むっつ', 'muttsu', 'six'],

      ['me'],

      ['目', 'め', 'me', 'eye'],
      ['メートル', 'メートル', 'meetoru', 'meter'],
      ['めがね', 'めがね', 'megane', 'a pair of glasses'],

      ['mo'],

      ['もう', 'もう', 'mou', 'already, yet'],
      ['もう', 'もう', 'mou', '(one) more'],
      ['木曜日', 'もくようび', 'mokuyoubi', 'Thursday'],
      ['もしもし', 'もしもし', 'moshimoshi', 'hello on the phone'],
      ['勿論', 'もちろん', 'mochiron', 'of course'],
      ['持つ', 'もつ', 'motsu', 'to have, to own'],
      ['もっと', 'もっと', 'motto', 'more'],
      ['物', 'もの', 'mono', 'thing'],
      ['門', 'もん', 'mon', 'gate'],
      ['問題', 'もんだい', 'mondai', 'problem, question'],

      ['ya'],

      ['〜屋', '〜や', '~ya', 'shop. store'],
      ['八百屋', 'やおや', 'yaoya', 'vegetable shop'],
      ['野菜', 'やさい', 'yasai', 'vegetable'],
      ['優しい', 'やさしい', 'yasashii', 'gentle'],
      ['安い', 'やすい', 'yasui', 'cheap, inexpensive'],
      ['休み', 'やすみ', 'yasumi', 'holiday, vacation'],
      ['休む', 'やすむ', 'yasumu', 'to rest'],
      ['八つ', 'やっつ', 'yattsu', 'eight'],
      ['山', 'やま', 'yama', 'mountain'],
      ['', 'やる', 'yaru', 'to do'],

      ['yo'],

      ['八日', 'ようか', 'youka', '8th day of the month, 8 days'],
      ['洋服', 'ようふく', 'youfuku', 'western style clothing'],
      ['よく', 'よく', 'yoku', 'often'],
      ['横', 'よこ', 'yoko', 'horizontal'],
      ['四日', 'よっか', 'yokka', '4th day of the month, 4 days'],
      ['四つ', 'よっつ', 'yottsu', 'four'],
      ['呼ぶ', 'よぶ', 'yobu', 'to call'],
      ['読む', 'よむ', 'yomu', 'to read'],
      ['夜', 'よる', 'yoru', 'night'],

      ['ra'],

      ['来月', 'らいげつ', 'raigetsu', 'next month'],
      ['来週', 'らいしゅう', 'raishuu', 'next week'],
      ['来年', 'らいねん', 'rainen', 'next year'],
      ['ラジオ', 'ラジオ', 'rajio', 'radio'],

      ['ri'],

      ['立派', 'りっぱ', 'rippa', 'splendid'],
      ['留学生', 'りゅうがくせい', 'ryuugakusei', 'foreign student'],
      ['両親', 'りょうしん', 'ryoushin', 'parents'],
      ['料理', 'りょうり', 'ryouri', 'cooking'],
      ['旅行', 'りょこう', 'ryokou', 'travel'],

      ['w'],

    ]
    return tab
  }
}

export { JapaneseStudy }
